[package]
name = "jaw"
version = "0.1.2"
edition = "2021"
authors = ["Artemij Artemev"]
keywords = ["cli", "read", "input"]
description = "tools to operate in cli"
license = "MIT"
repository = "https://github.com/wayfar9r/jaws.git"

[dependencies]


[dev-dependencies]
mocki = "0.1.1"
